### ISSUE TITLE
llfuse is broken on python 3.9 due to 2019 llfuse.c

### ISSUE THREAD

**Issue by ThomasWaldmann** [python-llfuse/python-llfuse#24]
see there: https://github.com/borgbackup/borg/issues/5372

@Nikratio I know llfuse is not maintained any more, but guess the fix to this issue would be to just cythonize llfuse.c with a more recent cython.

Would you do that and release it as 1.3.7 (or would you enable me to do that, alternatively)?

A lot of borgbackup users like `borg mount` which depends on this and was not yet ported to the pyfuse3 lib.

For our stable branch, such a big change is not advised anyway, but a lot of people use it on bleeding edge linuxes and likely will have a problem on python 3.9 soon.

**Comment by Nikratio** [comment]
I've recompiled with Cython 0.29.21 and released a new version. I wasn't able to upload to pypi though:

```
$ python3 setup.py upload
[...]
running upload
gpg --detach-sign -a dist/llfuse-1.3.7.tar.bz2
gpg: using "0xD113FCAC3C4E599F" as default secret key for signing
/home/nikratio/.local/lib/python3.7/site-packages/setuptools/command/upload.py:110: ResourceWarning: unclosed file <_io.BufferedReader name='dist/llfuse-1.3.7.tar.bz2.asc'>
  open(filename+".asc", "rb").read())
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Submitting dist/llfuse-1.3.7.tar.bz2 to https://upload.pypi.org/legacy/
Upload failed (400): Invalid file extension: Use .egg, .tar.gz, .whl or .zip extension. See https://www.python.org/dev/peps/pep-0527 for more information.
WARNING: Uploading via this command is deprecated, use twine to upload instead (https://pypi.org/p/twine/)
error: Upload failed (400): Invalid file extension: Use .egg, .tar.gz, .whl or .zip extension. See https://www.python.org/dev/peps/pep-0527 for more information.
```

**Comment by Nikratio** [comment]
I've invited you as a contributor to this project. If you have time available to work on this, this would be more than welcome.

Also happy to give you access to PyPi uploads, just let me know what exactly I need to do.

**Comment by ThomasWaldmann** [comment]
Thanks, I guess I can add twine / use twine to upload the release.

My pypi user name is `ThomasWaldmann`, you could add me there as additional owner so I could take care of it:

https://pypi.org/manage/project/llfuse/collaboration/
