### ISSUE TITLE
llfuse docs upload

### ISSUE THREAD

**Issue by ThomasWaldmann** [python-llfuse/python-llfuse#32]
this can only be done by @Nikratio.

would be "nice to have", but not super important as there are no functional or api changes.

**Comment by ThomasWaldmann** [comment]
https://pypi.org/project/llfuse/1.3.8/

**Comment by Nikratio** [comment]
done (from current master)

**Comment by ThomasWaldmann** [comment]
@Nikratio I just did a new release, can you upload the docs, please?

https://pypi.org/project/llfuse/1.4.0/
https://github.com/python-llfuse/python-llfuse/releases/tag/release-1.4.0

**Comment by Nikratio** [comment]
Done.

Would it be possible to move the docs to readthedocs.io or something similar? This may be a better choice in the long term.

(I think I always wanted to put them there but encountered some problem that I cannot remember anymore)

**Comment by ThomasWaldmann** [comment]
@Nikratio yeah, we can try that. #59
