### ISSUE TITLE
gcc8 patch

### ISSUE THREAD

**Issue by ThomasWaldmann** [python-llfuse/python-llfuse#34]
https://github.com/troels/python-llfuse-1/commit/328ea61db203e8389811a68b33e51ecc92c5b469

@Nikratio can you review? ^ maybe also interesting for pyfuse3?

**Comment by ThomasWaldmann** [comment]
todo: check if this still happens with a current cython release.

@troels can you comment on that? on my dev system, I still have gcc 6...

**Comment by troels** [comment]
Hi @ThomasWaldmann  

The unsigned char to int conversion issue, seems to have been fixed somewhere before cython 0.29.21. But the -Wcast-function-type problem is still there, and won't allow compilation with anything including and above gcc 8.

**Comment by ThomasWaldmann** [comment]
OK, I'll have a look at your patch before doing next release.

Guess it might be also related to that "developer mode" llfuse is (was) using - i changed they way this is triggered a while ago to avoid issues on build and ci systems and rather only have that if a developer activates it.

**Comment by ThomasWaldmann** [comment]
As I've recently upgraded my dev system to debian 10, I'll test on that / with gcc 8.3.0 now.

**Comment by ThomasWaldmann** [comment]
Using current master branch, I do not see any issue after setting `DEVELOPER_MODE=1`:
```
(python-llfuse-env) user@development:~/w/python-llfuse$ python setup.py build_cython
running in developer mode
running build_cython
Compiling /home/user/w/python-llfuse/src/llfuse.pyx
(python-llfuse-env) user@development:~/w/python-llfuse$ python setup.py build_ext
running in developer mode
running build_ext
building 'llfuse' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -I/home/user/w/python-llfuse-env/include/python3.7m -c src/llfuse.c -o build/temp.linux-x86_64-3.7/src/llfuse.o -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse -DFUSE_USE_VERSION=29 -Wall -Wextra -Wconversion -Wsign-compare -DLLFUSE_VERSION="1.3.8" -Wno-unused-function -Wno-implicit-fallthrough -Wno-unused-parameter -Werror -Wfatal-errors -Wno-error=unreachable-code -Werror=conversion -Werror=sign-compare
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -I/home/user/w/python-llfuse-env/include/python3.7m -c src/lock.c -o build/temp.linux-x86_64-3.7/src/lock.o -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse -DFUSE_USE_VERSION=29 -Wall -Wextra -Wconversion -Wsign-compare -DLLFUSE_VERSION="1.3.8" -Wno-unused-function -Wno-implicit-fallthrough -Wno-unused-parameter -Werror -Wfatal-errors -Wno-error=unreachable-code -Werror=conversion -Werror=sign-compare
creating build/lib.linux-x86_64-3.7
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.7/src/llfuse.o build/temp.linux-x86_64-3.7/src/lock.o -o build/lib.linux-x86_64-3.7/llfuse.cpython-37m-x86_64-linux-gnu.so -lfuse -pthread -lpthread -lrt
```

**Comment by ThomasWaldmann** [comment]
@troels Maybe due to dfb7d2ba3db8131cd348800c8d91df11bf930324 ?

So, guess this can be closed?

**Comment by ThomasWaldmann** [comment]
I did another try on a fresh fedora 33 install, using gcc 10.2.

I can't reproduce anything which was addressed by this patch, so I guess it is not needed any more.

I noticed another issue though and filed #55.
