### ISSUE TITLE
Rounding errors in dates

### ISSUE THREAD

**Issue by Grunthos** [python-llfuse/python-llfuse#37]
Nano-second values in excess of 999999500 cause rounding errors in file dates. 

This has the same root cause as reported for pyfuse3 ([here](https://github.com/libfuse/pyfuse3/issues/34)).

Is a patch desired, or is this library considered dead?

**Comment by ThomasWaldmann** [comment]
@Grunthos Thanks for finding/fixing that, I added some comments there.

llfuse is a requirement for `borgbackup` 1.1.x, so while it is officially unmaintained by @Nikratio I'll try to keep it alive while it is still needed by borg.

**Comment by ThomasWaldmann** [comment]
Fixed by #38.
