### ISSUE TITLE
"no longer maintained"?

### ISSUE THREAD

**Issue by ThomasWaldmann** [python-llfuse/python-llfuse#41]
considering that some people care a bit for keeping this working, i thought whether that hint in the readme should be rephrased.

so, maybe **"no longer developed"** would be a better fit?

**Comment by ThomasWaldmann** [comment]
@Nikratio what do you think?

**Comment by Nikratio** [comment]
Whatever you consider an accurate description is fine with me, it depends on your planned involvement :-).

**Comment by ThomasWaldmann** [comment]
Considering I don't know FUSE, I do not plan development.

But I can fix easy stuff, backport fixes from pyfuse3 and do maint releases here as long as it's still needed.

**Comment by ThomasWaldmann** [comment]
https://github.com/python-llfuse/python-llfuse

i updated the readme, but the "about" there ^^^ still says "unmaintained" (i have no access to change that).

**Comment by Nikratio** [comment]
Updated
