### ISSUE TITLE
llfuse setup.py forgets to report a non-zero status when libfuse headers are missing

### ISSUE THREAD

**Issue by callegar** [python-llfuse/python-llfuse#52]
Knowing that the project is not developed anymore, I think that it can still be good to report bugs to help users who may encounter similar situations.

The `setup.py` provided in llfuse gets invoked by `pip` when llfuse is installed via `pip`. In this case it is quite important to remember to return a non-zero status if something goes wrong, otherwise any error message produced by `setup.py` on its stderr goes lost.

One situation that may occur frequently is that llfuse's `setup.py` fails to find libfuse's headers files, which are needed in the setup phase. In this case, llfuse's `setup.py` does print a useful error message, however `pip` hides it, because llfuse's `setup.py` exits with a zero state as if no error happened. As a consequence, `pip` won't be able to provide any useful suggestion to the user.

**Comment by ThomasWaldmann** [comment]
Good catch!

Can you do a PR for this?

Maybe pyfuse3 (which is still developed) has the same issue?

**Comment by ThomasWaldmann** [comment]
@callegar did you see my reply?

**Comment by ThomasWaldmann** [comment]
I'm working on it...

**Comment by ThomasWaldmann** [comment]
Just returning rc=2 now for 2 failure cases related to pkg-config when detecting fuse lib and fuse version, then it behaves like this if libfuse-dev is not installed:

```
$ pip install dist/llfuse-1.4.0.tar.gz 
Processing ./dist/llfuse-1.4.0.tar.gz
    ERROR: Command errored out with exit status 2:
     command: /home/user/w/python-llfuse-env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-4zua7dl5/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-4zua7dl5/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-cbxpeyil
         cwd: /tmp/pip-req-build-4zua7dl5/
    Complete output (4 lines):
    Package fuse was not found in the pkg-config search path.
    Perhaps you should add the directory containing `fuse.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'fuse' found
    ----------------------------------------
ERROR: Command errored out with exit status 2: python setup.py egg_info Check the logs for full command output.
```

This is same behaviour as `pyfuse3` implements.

**Comment by ThomasWaldmann** [comment]
@callegar can you review #53 ?

**Comment by callegar** [comment]
@ThomasWaldmann unfortunately, I won't be able to take a look at it in a short time as I am dawning with my main job right now.

**Comment by ThomasWaldmann** [comment]
OK, no problem. Considering pyfuse3 does the same thing, guess it must be ok. :-)
