### ISSUE TITLE
move docs to readthedocs

### ISSUE THREAD

**Issue by ThomasWaldmann** [python-llfuse/python-llfuse#59]
so they automatically get pulled / generated / published when there is a new release.

**Comment by ThomasWaldmann** [comment]
@Nikratio I am trying to add llfuse to readthedocs.io, but I can't edit the repo settings on github due to missing permissions.

Can you either add me as admin or configure it by yourself?

**Comment by ThomasWaldmann** [comment]
Hmm, the sphinx docs building seems rather customized/patched in llfuse. I had a quick look at readthedocs configuration, but it didn't look like it can be tweaked like that.

Custom stuff:
- patch in setup.py
- extension util/sphinx_cython.py

Not sure about the rst / doc directory layout...

**Comment by Nikratio** [comment]
I think the `fix_docutils` stuff should no longer be needed, that was to work around an old Sphinx issue.

The sphinx extension should "just work", I believe.

Which repo settings do I need to change to what?

**Comment by ThomasWaldmann** [comment]
rtfd tells me: "The project llfuse doesn't have a valid webhook set up, commits won't trigger new builds for this project. See the project integrations for more information. "

It seems to want to add this webhook to github, but can't:

https://readthedocs.org/api/v2/webhook/llfuse/145604/

I do not have enough permissions, see https://docs.readthedocs.io/en/latest/webhooks.html .

**Comment by ThomasWaldmann** [comment]
My latest commit to master (fix sys.path so the sphinx extension in util/ is found) seems to make the build work.

But, it is not complete, this is rather empty:

https://llfuse.readthedocs.io/en/latest/fuse_api.html

**Comment by ThomasWaldmann** [comment]
@Nikratio i need your readthedocs.org username to add you as a maintainer there for llfuse docs.

**Comment by ThomasWaldmann** [comment]
Guess I have fixed the fuse api docs building. It needed to be able to import `llfuse` when running sphinx.

**Comment by ThomasWaldmann** [comment]
Hmm, nope. llfuse needs to be built (including cython, compiling C, using pkg-config to find fuse stuff, fuse headers/libs installed).

I tried with the "install project" option on rtfd, but it complains about not finding fuse (fuse.pc).

**Comment by ThomasWaldmann** [comment]
I was able to get the docs build working on rtd by adding a `.readthedocs.yaml` config file.

On the rtd side, the webhooks setup seems a bit weird (3 webhooks!?).
I can't check it on the github side as I don't have permissions for the project settings.

@Nikratio if you have some time, maybe have a look. also I still need your readthedocs email address or username to add you as maintainer there.

**Comment by ThomasWaldmann** [comment]
README should point to readthedocs. currently points to rath.org, but if i do a release, i can not update docs there.

docs on readthedocs should auto-update via webhook / gh integration.

**Comment by Nikratio** [comment]
Readthedocs username is Nikratio, thanks!

**Comment by ThomasWaldmann** [comment]
OK, I invited you to both llfuse and pyfuse3 readthedocs projects.

**Comment by ThomasWaldmann** [comment]
Merging PR #99 will complete this.
