### ISSUE TITLE
travis-ci needs to be migrated from .org to .com

### ISSUE THREAD

**Issue by ThomasWaldmann** [python-llfuse/python-llfuse#64]
we still have the ppc64le tests running there and .org will shut down soon.

guess only @Nikratio can do that, for me it says "not enough permissions".

**Comment by Nikratio** [comment]
What do you need me to do?

**Comment by ThomasWaldmann** [comment]
https://travis-ci.org/github/python-llfuse/python-llfuse

go there, log in and check your personal settings at the top right.

there should be an option for you to migrate the python-llfuse CI to travis.com.

**Comment by Nikratio** [comment]
Unfortunately not:

![image](https://user-images.githubusercontent.com/701625/106588977-58164200-6543-11eb-964f-358c6b68b846.png)

**Comment by ThomasWaldmann** [comment]
did you click on python-llfuse org there in the left sidebar?

**Comment by Nikratio** [comment]
That brings me here: 

![image](https://user-images.githubusercontent.com/701625/106598255-69654b80-654f-11eb-8d39-5bae142e0a5d.png)

..still not sure where to migrate unfortunately.

**Comment by Nikratio** [comment]
I found this promising page when going to travis-ci.com:

![image](https://user-images.githubusercontent.com/701625/106598573-d7117780-654f-11eb-8ed9-314878c0e4fd.png)


Unfortunately, clicking the button brings me here:

![image](https://user-images.githubusercontent.com/701625/106598548-cbbe4c00-654f-11eb-91f9-2d1aa0ab0343.png)

**Comment by ThomasWaldmann** [comment]
Did you already activate the "free" plan on travis.com?

**Comment by ThomasWaldmann** [comment]
It also seems that nowadays one needs to "sign up for beta" with travis-ci to be able to migrate (that wasn't the case last time i migrated some of my stuff - but it was a rather confusing process, too).

**Comment by ThomasWaldmann** [comment]
Hmm, I don't see travis-ci active here any more.

Guess I'll just remove its config from the project and we're done with it.
Did this for most of my projects also.
