### ISSUE TITLE
Missing package dependency on setuptools

### ISSUE THREAD

**Issue by HubTou** [python-llfuse/python-llfuse#70]
On a machine without the wheel and setuptools packages:

# pip install llfuse
Collecting llfuse
  Using cached llfuse-1.4.2.tar.gz (834 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-iikz65us/llfuse_4edcb73ffee0452aa882e70ba3b92e0a/setup.py", line 40, in <module>
          from setuptools import Extension
      **ImportError: cannot import name 'Extension' from 'setuptools' (unknown location)**
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

# pip install setuptools
Collecting setuptools
  Using cached setuptools-62.6.0-py3-none-any.whl (1.2 MB)
Installing collected packages: setuptools
Successfully installed setuptools-62.6.0

# pip install llfuse
Collecting llfuse
  Using cached llfuse-1.4.2.tar.gz (834 kB)
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for llfuse, since package 'wheel' is not installed.
Installing collected packages: llfuse
  Running setup.py install for llfuse ... done
Successfully installed llfuse-1.4.2

# Fix
I suggest adding the following to your setup.py file, for example after "python_requires":

```python
install_requires=[
          'setuptools',
      ],
```

**Comment by ThomasWaldmann** [comment]
Isn't it rather `setup_requires` because it is needed at setup time, but not later for normal usage?

Also, guess it does not even help there, as the import is done on module level of setup.py, so it is needed before setup() is even called.

So, guess what we really need here for this purpose is a `pyproject.toml`.

**Comment by HubTou** [comment]
Hi Thomas.
You're probably right. Something [like this](https://github.com/HubTou/b2bt/blob/main/pyproject.toml), I guess.

**Comment by ThomasWaldmann** [comment]
Not sure if we should require wheel, should we?

**Comment by HubTou** [comment]
Yes, try first with the strict minimum
