### ISSUE TITLE
python 3.12 support

### ISSUE THREAD

**Issue by sergey-dryabzhinsky** [python-llfuse/python-llfuse#73]
Version: 1.4.2
System: Ubuntu 18.04 amd64
libfuse: 2.9.7-1ubuntu1
python: 3.12.0~a7

It can't be compiled over 3.12.0~a7. They changed internal structures again.
Errors and warnings in log file.
[build-llfuse-1.4.2-against-python3.12.0a7-ubuntu1804.log.gz](https://github.com/python-llfuse/python-llfuse/files/11412677/build-llfuse-1.4.2-against-python3.12.0a7-ubuntu1804.log.gz)

**Comment by ThomasWaldmann** [comment]
Besides some deprecation warnings, this error seems to be the main problem:
```
src/llfuse.c: In function ‘__Pyx_PyInt_As_time_t’:
src/llfuse.c:58504:53: error: ‘PyLongObject {aka struct _longobject}’ has no member named ‘ob_digit’
             const digit* digits = ((PyLongObject*)x)->ob_digit;
                                                     ^~
```

**Comment by ThomasWaldmann** [comment]
@sergey-dryabzhinsky thanks for reporting this, I filed a bug at the cython project - let's see what they say.

**Comment by sergey-dryabzhinsky** [comment]
@ThomasWaldmann I don't cythonize anything, just `python3.12 setup.py build_ext`.
I'll try to cythonize.

**Comment by sergey-dryabzhinsky** [comment]
Hm, seems valid commands are:
1. install latest cython: `pip3.12 install --update --user cython`
2. make cython build: `DEVELOPER_MODE=1 python3.12 setup.py build_cython`
3. make extension: `python3.12 setup.py build_ext`

**Comment by sergey-dryabzhinsky** [comment]
It compiles fine with python3.{4,5,6,7,8,9,10,11,12} after recythonize.
So, maybe you need to update release with generated by new cython file.

**Comment by ThomasWaldmann** [comment]
Yeah, I'll create a new release soon. Thanks for investigating this.

**Comment by ThomasWaldmann** [comment]
@sergey-dryabzhinsky 1.4.3 is released, can you give it a practical test?

**Comment by sergey-dryabzhinsky** [comment]
@ThomasWaldmann 
Tested version 1.4.4 via 3.12.0~b1 - builds fine.
